# graph/state.py
from typing import TypedDict, Literal

class GraphState(TypedDict):
    """
    Represents the state of our graph.

    Attributes:
        query: The initial user query.
        data_source: The data source selected by the router ('sqlite' or 'mongodb').
        generated_query: The database-specific query generated by the specialized agent.
        context: The data retrieved from the database.
        response: The final natural language response to the user.
        error: A field to capture any errors during the process.
    """
    query: str
    data_source: Literal["sqlite", "mongodb", "end"]
    generated_query: str
    context: str
    response: str
    error: str